//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehin_versión2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string TipoDoc { get; set; }
        public string NumeroDoc { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Domicilio { get; set; }
        public string Foto { get; set; }
        public int LocalidadesId { get; set; }
        public int ClientesId { get; set; }
    
        public virtual Localidades Localidades { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
