//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehin_versión2._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloContainer : DbContext
    {
        public ModeloContainer()
            : base("name=ModeloContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> ClientesSet { get; set; }
        public virtual DbSet<Establecimientos> EstablecimientosSet { get; set; }
        public virtual DbSet<Contacto> ContactoSet { get; set; }
        public virtual DbSet<Presupuesto> PresupuestoSet { get; set; }
        public virtual DbSet<DetallePresupuesto> DetallePresupuestoSet { get; set; }
        public virtual DbSet<Técnicos> TécnicosSet { get; set; }
        public virtual DbSet<Agenda> AgendaSet { get; set; }
        public virtual DbSet<Puestos> PuestosSet { get; set; }
        public virtual DbSet<Trabajadores> TrabajadoresSet { get; set; }
        public virtual DbSet<Máquinas> MáquinasSet { get; set; }
        public virtual DbSet<Riesgos> RiesgosSet { get; set; }
        public virtual DbSet<TipoRiesgos> TipoRiesgosSet { get; set; }
        public virtual DbSet<Accidentes> AccidentesSet { get; set; }
        public virtual DbSet<MedidasPreventivas> MedidasPreventivasSet { get; set; }
        public virtual DbSet<OrdenTrabajo> OrdenTrabajoSet { get; set; }
        public virtual DbSet<PlanesFormacion> PlanesFormacionSet { get; set; }
        public virtual DbSet<DetallePlanesFormacion> DetallePlanesFormacionSet { get; set; }
        public virtual DbSet<Cursos> CursosSet { get; set; }
        public virtual DbSet<CondicionIva> CondicionIvaSet { get; set; }
        public virtual DbSet<Provincias> ProvinciasSet { get; set; }
        public virtual DbSet<Localidades> LocalidadesSet { get; set; }
        public virtual DbSet<ActividadesEconomicas> ActividadesEconomicasSet { get; set; }
        public virtual DbSet<Tareas> TareasSet { get; set; }
        public virtual DbSet<Servicio> ServicioSet { get; set; }
        public virtual DbSet<ClasePrueba> ClasePruebaSet { get; set; }
    }
}
