//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehin_versión2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenTrabajo()
        {
            this.Agenda = new HashSet<Agenda>();
        }
    
        public int Id { get; set; }
        public int PuestosId { get; set; }
        public int TrabajadoresId { get; set; }
        public int MáquinasId { get; set; }
        public int RiesgosId { get; set; }
        public int MedidasPreventivasId { get; set; }
        public int TareasId { get; set; }
    
        public virtual Puestos Puestos { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
        public virtual Máquinas Máquinas { get; set; }
        public virtual Riesgos Riesgos { get; set; }
        public virtual MedidasPreventivas MedidasPreventivas { get; set; }
        public virtual Tareas Tareas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
    }
}
